[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  node_bundler = "esbuild"
